services:
  springapp:
    image: shahir5890/spring-boot:IMAGE_TAG
    ports:
    - 8080:8080
    depends_on:
    - mongo
    networks:
    - springappbridge
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
  mongo:
    image: mongo
    networks:
    - springappbridge
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
    - mongovol:/data/db
networks:
  springappbridge:
    driver: bridge
volumes:
  mongovol:
    driver: local
